name: CI
on: [push]
jobs:
  build_and_test:
    name: Rust project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Get rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Generate package (crate file)
        run: cargo package
      - name: Upload package (crate file)
        uses: actions/upload-artifact@v2
        with:
          name: crate
          path: target/package/mtxstuff-*.crate
      #- name: Build binary
      #  run: cargo build --release
      #- name: Upload binary
      #  uses: actions/upload-artifact@v2
      #  with:
      #    name: mtxstuff_binary
      #    path: target/release/mtxstuff