name: CI
on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  build_and_test:
    name: Rust project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Build binary
        run: cargo build --release

      - name: Archive Binary
        run: tar -czf mtxstuff-${{ github.ref_name }}-amd64.tar.gz -C target/release/ mtxstuff

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: mtxstuff-${{ github.ref_name }}-amd64.tar.gz
